name: build-and-publish
on:
  push:
    branches: [master, main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Gitea registry
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login git.thebennett.net -u "${{ secrets.REGISTRY_USER }}" --password-stdin
      - name: Build + push
        run: |
          docker build -t git.thebennett.net/reformedwitness/rwn-website:latest -t git.thebennett.net/reformedwitness/rwn-website:${{ github.sha }} .
          docker push git.thebennett.net/reformedwitness/rwn-website:latest
          docker push git.thebennett.net/reformedwitness/rwn-website:${{ github.sha }}
